version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BBpCuomoUMgWJTOPikrXDaljusLqoRCO 
      POSTGRES_DB: railway
    ports:
      - 5494:5432
