version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0518
      POSTGRES_DB: marketplacedb
    ports:
      - 5494:5432